### ISSUE TITLE
git lfs pull: This repo is over its data quota

### ISSUE THREAD

**Issue by LucaFos** [autowarefoundation/modelzoo#10]
Looks like the git lfs quota for this repo is currently zero.
Steps to reproduce:
```
$ GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/autowarefoundation/modelzoo.git
Cloning into 'modelzoo'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 110 (delta 31), reused 88 (delta 19), pack-reused 0
Receiving objects: 100% (110/110), 34.83 KiB | 524.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
$ cd modelzoo
$ git lfs pull
Git LFS: (0 of 4 files) 0 B / 80.34 MB
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/autowarefoundation/modelzoo.git/info/lfs'
```

**Comment by JWhitleyWork** [comment]
@LucaFos Thanks for bringing this up. I've purchased some "Github Data Packs" which have corrected the problem for now. However, this is probably something we want to handle differently in the future instead of continuing to pay Github $10/mo.

@LiyouZhou Our current Quota limit without paying is 1GB of storage and 1GB of transfer bandwidth per month. A Data Pack adds 50GB of storage and 50GB of bandwidth. I bought 2 so that gives us 100GB of each, which I don't see us hitting short-term. However, an additional problem is that the maximum file size for any individual file is 100MB, which I'm guessing we may exceed. Github does not allow you to use an external LFS back-end (such as S3) by default.

Some alternatives:

- Host our own LFS forwarding server that forwards LFS files to S3
  - Something like https://blog.dermah.com/2020/05/26/how-to-be-stingy-git-lfs-on-your-own-s3-bucket/ or https://github.com/troyready/git-lfs-s3
  - Downside is that we have to manage this server. Running it basically costs nothing because it can be a free-tier AWS EC2 instance
- Move back to gitlab.com
  - The repository limit is 10GB and there is no bandwidth usage limitation
- Use another storage mechanism (instead of `git lfs`) for trained files
  - e.g. using S3 with links that are parsed by a `bash` file and downloaded that way
  - The downside is that we don't get version control, which I think we want
- Continue paying $10/mo
  - I paid with my credit card this time but we should get an AWF card if we continue this path.

Any feedback would be appreciated.

**Comment by LiyouZhou** [comment]
I would say
> Continue paying $10/mo 
There is no sense spending engineering time implementing and maintaining an s3 solution. The engineering time is likely to be more expensive.

> maximum file size
This might issue. but [this](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/about-storage-and-bandwidth-usage) suggest we should be able to push large files. Maybe the 100mb limit is for git regular files?

**Comment by JWhitleyWork** [comment]
It looks like you are correct. I mis-interpreted [this page](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/conditions-for-large-files) as also applying to `git lfs` (which it does not).

For the time being, we'll continue with the $10/mo.
